// there is an enum conversion warning in a GCC header
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-enum-enum-conversion"

#include <gcc-plugin.h>
#include <tree.h>                // DECL_NAME
#include <tree-core.h>           // ECF_NORETURN
#include <tree-cfg.h>            // label_to_block
#include <function.h>            // function
#include <gimple.h>              // gimple_location
#include <gimple-iterator.h>     // gimple_stmt_iterator, gsi_start_bb, gsi_end_p, gsi_next, gsi_stmt
#include <gimple-pretty-print.h> // debug_gimple_stmt
#include <internal-fn.h>         // internal_fn_name
#include <wide-int-print.h>
#include <print-tree.h>
#include "coretypes.h"

#pragma GCC diagnostic pop

#include "DiagnosticLevel.hpp"
#include "FunctionId.hpp"
#include "FunctionType.hpp"
#include "GCCAdapter.hpp"
#include "Instruction.hpp"
#include "Operand.hpp"
#include "SourceLocation.hpp"
#include "SwitchCase.hpp"
#include "Type.hpp"
#include "TypeId.hpp"
#include "TypeKind.hpp"
#include "Variable.hpp"
#include "VariableId.hpp"

namespace CodeListener::CompilerAbstractionLayer
{

GCCAdapter::GCCAdapter(Core::CodeModel &model, Core::DiagnosticReporter &reporter) : model(model), reporter(reporter)
{
    reporter.report(Core::DiagnosticLevel::Debug, std::string("Initialized GCCAdapter"));
}

Core::TypeKind GCCAdapter::mapTypeTreeToTypeKind(tree &type_tree)
{
    if (!type_tree)
    {
        reporter.report(Core::DiagnosticLevel::Warning, "Encountered a null type tree, treating as UNKNOWN");
        return Core::TypeKind::UNKNOWN;
    }

    switch (TREE_CODE(type_tree))
    {
    // case OFFSET_TYPE
    case ENUMERAL_TYPE:
        return Core::TypeKind::ENUM;
    case BOOLEAN_TYPE:
        return Core::TypeKind::BOOL;
    case INTEGER_TYPE:
        return Core::TypeKind::INTEGER;
    case REAL_TYPE:
        return Core::TypeKind::REAL;
    case POINTER_TYPE:
    case REFERENCE_TYPE:
        return Core::TypeKind::POINTER;
    // case NULLPTR_TYPE:
    // case FIXED_POINT_TYPE:
    // case COMPLEX_TYPE:
    // case VECTOR_TYPE:
    case ARRAY_TYPE:
        return Core::TypeKind::ARRAY;
    case RECORD_TYPE:
        return Core::TypeKind::STRUCT;
    case UNION_TYPE:
        return Core::TypeKind::UNION;
    // case QUAL_UNION_TYPE:
    case VOID_TYPE:
        return Core::TypeKind::VOID;
    case FUNCTION_TYPE:
    case METHOD_TYPE:
        return Core::TypeKind::FUNCTION;
    // case COMPLEX_TYPE:
    //     return Core::TypeKind::COMPLEX;
    default:
        return Core::TypeKind::UNKNOWN;
    }
}

location_t GCCAdapter::enhanceLocationT(location_t location, enum gimple_code gcode, gimple *stmt)
{
    if (location != UNKNOWN_LOCATION && location > BUILTINS_LOCATION)
    {
        return location;
    }

    switch (gcode)
    {
    case GIMPLE_LABEL: {
        tree label = gimple_label_label(as_a<glabel *>(stmt));
        if (label && DECL_SOURCE_LOCATION(label) != UNKNOWN_LOCATION)
        {
            location = DECL_SOURCE_LOCATION(label);
        }
    }
    break;
    case GIMPLE_RETURN: {
        if (cfun && cfun->function_end_locus != UNKNOWN_LOCATION)
        {
            location = cfun->function_end_locus;
        }
    }
    break;
    default:
        reporter.report(Core::DiagnosticLevel::Debug,
                        "No location (" + std::to_string(location) + ") enhancement needed for gimple code " +
                            gimple_code_name[gcode] + ", using original location which may be unknown");
        break;
    }

    return location;
}

Core::SourceLocation GCCAdapter::getSourceLocation(location_t location)
{
    if (location == UNKNOWN_LOCATION || location <= BUILTINS_LOCATION)
    {
        // FIXME: before return statement, there is a label to jump to unknown location for some reason
        // = the location of the label and return is UNKNOWN, because the block with them is generated by GCC
        reporter.report(Core::DiagnosticLevel::Warning, "Encountered an unknown source location");

        return Core::SourceLocation();
    }

    expanded_location eloc = expand_location(location);
    if (eloc.file == nullptr)
    {
        reporter.report(Core::DiagnosticLevel::Warning, "Encountered an unknown source location");

        return Core::SourceLocation();
    }

    return Core::SourceLocation(eloc.file, current_function_name, eloc.line, eloc.column);
}

Core::TypeId GCCAdapter::getOrCreateType(tree type_tree)
{
    if (!type_tree)
    {
        reporter.report(Core::DiagnosticLevel::Warning, "Encountered a type without a tree representation");
        return Core::TypeId::invalid();
    }

    if (type_cache.count(type_tree))
    {
        reporter.report(Core::DiagnosticLevel::Debug, "Type already processed, reusing existing node");
        return type_cache[type_tree];
    }

    Core::Type *type = model.createType();
    reporter.report(Core::DiagnosticLevel::Debug, "Processing a new type with ID: " + std::to_string(type->id) + "...");

    // pre-insert into cache to handle recursive types
    type_cache[type_tree] = type->id;

    // extract type name
    if (TYPE_NAME(type_tree) && TREE_CODE(TYPE_NAME(type_tree)) == TYPE_DECL && DECL_NAME(TYPE_NAME(type_tree)))
    {
        type->name = IDENTIFIER_POINTER(DECL_NAME(TYPE_NAME(type_tree)));
    }
    else
    {
        reporter.report(Core::DiagnosticLevel::Warning,
                        "Type does not have a name or has an unsupported name tree structure");
    }
    reporter.report(Core::DiagnosticLevel::Debug, "Type name extracted as: " + type->name);

    type->kind = mapTypeTreeToTypeKind(type_tree);

    type->is_const = TYPE_READONLY(type_tree);
    type->is_volatile = TYPE_VOLATILE(type_tree);
    type->is_atomic = TYPE_ATOMIC(type_tree);

    if (TYPE_SIZE(type_tree) && TREE_CODE(TYPE_SIZE(type_tree)) == INTEGER_CST &&
        tree_fits_uhwi_p(TYPE_SIZE(type_tree)))
    {
        type->size_bits = tree_to_uhwi(TYPE_SIZE(type_tree));
    }
    // no else branch because this is regurarly the case for types like void that don't have a size, and we can just
    // leave size_bits as 0 for them

    type->alignment = TYPE_ALIGN_UNIT(type_tree);

    // handle type-specific information
    switch (TREE_CODE(type_tree))
    {
        // case OFFSET_TYPE:

    case BOOLEAN_TYPE: {
        type->data = Core::BoolType{};
    }
    break;

    case ENUMERAL_TYPE: {
        type->data = Core::EnumType{.is_unsigned = (bool)TYPE_UNSIGNED(type_tree)};
    }
    break;

    case INTEGER_TYPE: {
        type->data = Core::IntegerType{(bool)TYPE_UNSIGNED(type_tree)};
    }
    break;

    case REAL_TYPE: {
        if (TYPE_MODE(type_tree) == BLKmode)
        {
            reporter.report(Core::DiagnosticLevel::Warning, "Encountered a real type with BLKmode, which may indicate "
                                                            "an unsupported or complex floating-point type.");
        }
        type->data = Core::FloatType{};
    }
    break;

    case POINTER_TYPE:
    case REFERENCE_TYPE: {
        type->data = Core::PointerType{.pointee_type_id = getOrCreateType(TREE_TYPE(type_tree)),
                                       .is_restrict = (bool)TYPE_RESTRICT(type_tree)};
    }
    break;

        // case NULLPTR_TYPE:
        // case FIXED_POINT_TYPE:
        // case COMPLEX_TYPE:
        // case VECTOR_TYPE:

    case ARRAY_TYPE: {
        Core::ArrayType array_type;
        array_type.element_type_id = getOrCreateType(TREE_TYPE(type_tree));
        if (TYPE_DOMAIN(type_tree))
        {
            tree max = TYPE_MAX_VALUE(TYPE_DOMAIN(type_tree));
            if (max && TREE_CODE(max) == INTEGER_CST && tree_fits_uhwi_p(max))
            {
                array_type.element_count = tree_to_uhwi(max) + 1;
            }
            else
            {
                reporter.report(Core::DiagnosticLevel::Warning,
                                "Array type has a VLA or non-constant domain max, treating as having unknown size");
                array_type.element_count = std::nullopt;
            }
        }
        else
        {
            reporter.report(Core::DiagnosticLevel::Warning,
                            "Array type does not have a domain, treating as having unknown size");
            array_type.element_count = std::nullopt;
        }
        type->data = std::move(array_type);
    }
    break;

    case RECORD_TYPE: {
        Core::StructType struct_type;

        for (tree field = TYPE_FIELDS(type_tree); field; field = DECL_CHAIN(field))
        {
            if (TREE_CODE(field) == FIELD_DECL)
            {
                Core::VariableId field_id = getOrCreateVariable(field);
                struct_type.fields.push_back(field_id);
            }
        }

        type->data = std::move(struct_type);
    }
    break;

    case UNION_TYPE: {
        Core::UnionType union_type;

        for (tree field = TYPE_FIELDS(type_tree); field; field = DECL_CHAIN(field))
        {
            if (TREE_CODE(field) == FIELD_DECL)
            {
                Core::VariableId field_id = getOrCreateVariable(field);
                union_type.fields.push_back(field_id);
            }
        }

        type->data = std::move(union_type);
    }
    break;

        // case QUAL_UNION_TYPE:

    case VOID_TYPE: {
        type->data = Core::VoidType{};
    }
    break;

    case FUNCTION_TYPE:
    case METHOD_TYPE: {
        Core::FunctionType function_type;

        function_type.return_type_id = getOrCreateType(TREE_TYPE(type_tree));

        for (tree arg = TYPE_ARG_TYPES(type_tree); arg; arg = TREE_CHAIN(arg))
        {
            if (TREE_VALUE(arg) == void_type_node)
            {
                break;
            }

            function_type.parameter_type_ids.push_back(getOrCreateType(TREE_VALUE(arg)));
        }

        type->data = std::move(function_type);
    }
    break;
        // case LANG_TYPE:
        // case OPAQUE_TYPE:

    default:
        reporter.report(Core::DiagnosticLevel::Warning, "Unhandled type tree code: " + type->name + "(" +
                                                            std::to_string(TREE_CODE(type_tree)) +
                                                            "), treating as UNKNOWN");
        type->data = Core::UnknownType{};
        break;
    }

    return type->id;
}

Core::Initializer GCCAdapter::parseInitializer(tree init_tree)
{
    if (!init_tree)
    {
        return Core::ConstantOperand{Core::TypeId::invalid(), "<null>"};
    }

    // strip NOPs (type casts) that GCC sometimes wraps around initializers
    while (TREE_CODE(init_tree) == NOP_EXPR)
    {
        init_tree = TREE_OPERAND(init_tree, 0);
    }

    if (TREE_CODE(init_tree) == CONSTRUCTOR)
    {
        // recursively parse nested arrays/structs
        auto init_list = std::make_shared<Core::InitializerList>();

        unsigned HOST_WIDE_INT idx;
        tree index_tree [[maybe_unused]];
        tree value;
        FOR_EACH_CONSTRUCTOR_ELT(CONSTRUCTOR_ELTS(init_tree), idx, index_tree, value)
        {
            init_list->elements.push_back(parseInitializer(value));
        }

        return init_list;
    }
    else if (TREE_CODE(init_tree) == STRING_CST)
    {
        // special case: strings are technically arrays of chars, but usually kept as constants
        return Core::ConstantOperand{getOrCreateType(TREE_TYPE(init_tree)),
                                     std::string(TREE_STRING_POINTER(init_tree), TREE_STRING_LENGTH(init_tree))};
    }

    // base case: it's just a regular operand (INTEGER_CST, REAL_CST, or an address of a variable)
    return parseOperand(init_tree);
}

Core::VariableId GCCAdapter::getOrCreateVariable(tree variable_tree)
{
    if (!variable_tree)
    {
        reporter.report(Core::DiagnosticLevel::Warning, "Encountered a variable without a tree representation");
        return Core::VariableId::invalid();
    }

    if (variable_cache.count(variable_tree))
    {
        reporter.report(Core::DiagnosticLevel::Debug, "Variable already processed, reusing existing node");
        return variable_cache[variable_tree];
    }

    Core::Variable *variable = model.createVariable();
    reporter.report(Core::DiagnosticLevel::Debug,
                    "Processing a new variable with ID: " + std::to_string(variable->id) + "...");

    // pre-insert into cache to handle recursive variables (e.g. struct fields referencing the struct type)
    variable_cache[variable_tree] = variable->id;

    // build universal variable properties
    variable->type_id = getOrCreateType(TREE_TYPE(variable_tree));

    if (DECL_P(variable_tree) && DECL_NAME(variable_tree))
    {
        const char *name = IDENTIFIER_POINTER(DECL_NAME(variable_tree));
        variable->name = name ? name : "<anonymous>";
    }
    else if (TREE_CODE(variable_tree) == SSA_NAME)
    {
        // Try to follow trivial SSA assignment chains to find an underlying named VAR_DECL
        // mathces traverse_ssa_names()/get_decl_name() behavior
        tree resolved = variable_tree;
        const int max_depth = 4;
        bool found_named_var = false;
        for (int depth = 0; depth < max_depth; ++depth)
        {
            gimple *def_stmt = SSA_NAME_DEF_STMT(resolved);
            if (!def_stmt || gimple_code(def_stmt) != GIMPLE_ASSIGN)
            {
                break;
            }
            if (gimple_num_ops(def_stmt) != 2)
            {
                break;
            }
            if (gimple_assign_lhs(def_stmt) != resolved)
            {
                break;
            }
            // only follow trivial (ASSIGN = identity copy) operations
            enum tree_code rhs_code = gimple_assign_rhs_code(def_stmt);
            if (rhs_code != NOP_EXPR && rhs_code != VAR_DECL && rhs_code != SSA_NAME)
            {
                break;
            }
            tree rhs = gimple_assign_rhs1(def_stmt);
            if (!rhs)
            {
                break;
            }
            enum tree_code rhs_tree_code = TREE_CODE(rhs);
            if (rhs_tree_code == VAR_DECL || rhs_tree_code == PARM_DECL)
            {
                if (DECL_NAME(rhs))
                {
                    const char *name = IDENTIFIER_POINTER(DECL_NAME(rhs));
                    variable->name = name ? name : "";
                    found_named_var = true;
                }
                break;
            }
            else if (rhs_tree_code == SSA_NAME)
            {
                resolved = rhs;
                continue;
            }
            else
            {
                break;
            }
        }
        if (!found_named_var)
        {
            // empty name if no DECL_NAME
            variable->name = "";
        }
    }
    // for labels and DECL_Ps using GCC's native artificial label/variable naming convention (e.g., L42 or D.42)
    else if (TREE_CODE(variable_tree) == LABEL_DECL)
    {
        variable->artificial = DECL_ARTIFICIAL(variable_tree);
        if (DECL_NAME(variable_tree))
        {
            variable->name = IDENTIFIER_POINTER(DECL_NAME(variable_tree));
        }
        else
        {
            variable->name = "L" + std::to_string(DECL_UID(variable_tree));
        }
    }
    else if (DECL_P(variable_tree))
    {
        // empty name if no DECL_NAME
        variable->name = "";
    }
    reporter.report(Core::DiagnosticLevel::Debug, "Variable name extracted as: " + variable->name);

    if (DECL_P(variable_tree))
    {
        variable->artificial = DECL_ARTIFICIAL(variable_tree);
        variable->source_location = getSourceLocation(DECL_SOURCE_LOCATION(variable_tree));
    }
    else if (TREE_CODE(variable_tree) == SSA_NAME)
    {
        tree var = SSA_NAME_VAR(variable_tree);
        variable->artificial = (var && DECL_P(var)) ? DECL_ARTIFICIAL(var) : true;
    }

    // build specific variable variant data
    switch (TREE_CODE(variable_tree))
    {
    case FIELD_DECL: {
        Core::FieldVariable field_var;

        unsigned offset_bits = 0;
        if (DECL_FIELD_OFFSET(variable_tree) && tree_fits_uhwi_p(DECL_FIELD_OFFSET(variable_tree)))
        {
            offset_bits += tree_to_uhwi(DECL_FIELD_OFFSET(variable_tree)) * 8;
        }
        if (DECL_FIELD_BIT_OFFSET(variable_tree) && tree_fits_uhwi_p(DECL_FIELD_BIT_OFFSET(variable_tree)))
        {
            offset_bits += tree_to_uhwi(DECL_FIELD_BIT_OFFSET(variable_tree));
        }
        field_var.byte_offset = offset_bits / 8;

        if (DECL_BIT_FIELD(variable_tree))
        {
            if (DECL_SIZE(variable_tree) && tree_fits_uhwi_p(DECL_SIZE(variable_tree)))
            {
                field_var.bitfield_size = tree_to_uhwi(DECL_SIZE(variable_tree));
            }
            if (DECL_FIELD_BIT_OFFSET(variable_tree) && tree_fits_uhwi_p(DECL_FIELD_BIT_OFFSET(variable_tree)))
            {
                field_var.bitfield_offset = tree_to_uhwi(DECL_FIELD_BIT_OFFSET(variable_tree));
            }
        }

        variable->data = std::move(field_var);
    }
    break;

        // TODO: handle other specific variable declaration types if needed, e.g. CONST_DECL for enum constants,
        // TYPE_DECL for typedefs, etc. For now, treating them all as standard variables with best-effort processing.

    case LABEL_DECL:

        // case CONST_DECL:
        // case TYPE_DECL:

        // case DEBUG_EXPR_DECL:
        // case NAMESPACE_DECL:
        // case IMPORTED_DECL:
        // case NAMELIST_DECL:
        // case TRANSLATION_UNIT_DECL:

    case FUNCTION_DECL:
    case VAR_DECL:
    case PARM_DECL:
    case RESULT_DECL:
    case SSA_NAME: {
        Core::StandardVariable std_var;

        // scope
        if (TREE_CODE(variable_tree) == SSA_NAME || TREE_CODE(variable_tree) == PARM_DECL ||
            TREE_CODE(variable_tree) == RESULT_DECL)
        {
            std_var.scope = Core::Scope::FUNCTION;
        }
        else if (TREE_CODE(variable_tree) == FUNCTION_DECL || is_global_var(variable_tree))
        {
            if (TREE_CODE(variable_tree) == VAR_DECL && TREE_STATIC(variable_tree) && !DECL_EXTERNAL(variable_tree))
            {
                std_var.scope = Core::Scope::STATIC;
            }
            else
            {
                std_var.scope = Core::Scope::GLOBAL;
            }
        }
        else
        {
            std_var.scope = Core::Scope::FUNCTION;
        }

        // storage duration and linkage
        if (TREE_CODE(variable_tree) == PARM_DECL || TREE_CODE(variable_tree) == RESULT_DECL ||
            TREE_CODE(variable_tree) == SSA_NAME)
        {
            std_var.storage_duration = Core::StorageDuration::AUTO;
            std_var.linkage = Core::Linkage::NONE;
        }
        else if (TREE_STATIC(variable_tree))
        {
            std_var.storage_duration = Core::StorageDuration::STATIC;
            std_var.linkage = TREE_PUBLIC(variable_tree) ? Core::Linkage::EXTERNAL : Core::Linkage::INTERNAL;
        }
        else if (DECL_EXTERNAL(variable_tree))
        {
            std_var.storage_duration = Core::StorageDuration::EXTERN;
            std_var.linkage = Core::Linkage::EXTERNAL;
        }
        else if (DECL_REGISTER(variable_tree))
        {
            std_var.storage_duration = Core::StorageDuration::REGISTER;
            std_var.linkage = Core::Linkage::NONE;
        }
        else
        {
            std_var.storage_duration = Core::StorageDuration::AUTO;
            std_var.linkage = Core::Linkage::NONE;
        }

        if (DECL_P(variable_tree) && DECL_THREAD_LOCAL_P(variable_tree))
        {
            std_var.storage_duration = Core::StorageDuration::THREAD_LOCAL;
        }

        // initializer parsing
        if (TREE_CODE(variable_tree) == VAR_DECL && DECL_INITIAL(variable_tree))
        {
            std_var.initial_value = parseInitializer(DECL_INITIAL(variable_tree));
        }

        variable->data = std::move(std_var);
    }
    break;

        // case TEMPLATE_DECL:
        // case USING_DECL:
        // case CONCEPT_DECL:
        // case WILDCARD_DECL:
        // case KEYWORD_DECL:
        // case INSTANCE_METHOD_DECL:
        // case CLASS_METHOD_DECL:
        // case PROPERTY_DECL:

    default:
        reporter.report(Core::DiagnosticLevel::Warning,
                        "Unhandled variable tree code: " + std::to_string(TREE_CODE(variable_tree)) +
                            ", treating as a standard variable with best-effort processing");
        variable->data = Core::StandardVariable{};
        break;
    }

    return variable->id;
}

Core::Operand GCCAdapter::parseOperand(tree operand_tree)
{
    if (!operand_tree)
    {
        return Core::ConstantOperand{Core::TypeId::invalid(), "<null>"};
    }

    // handle constants
    if (CONSTANT_CLASS_P(operand_tree))
    {
        reporter.report(Core::DiagnosticLevel::Debug, "Processing operand as constant operand...");

        Core::ConstantOperand constant_operand;
        constant_operand.type_id = getOrCreateType(TREE_TYPE(operand_tree));

        switch (TREE_CODE(operand_tree))
        {
            // case VOID_CST:

        case INTEGER_CST:
            if (TYPE_UNSIGNED(TREE_TYPE(operand_tree)))
            {
                constant_operand.value = std::to_string(tree_to_uhwi(operand_tree));
            }
            else
            {
                constant_operand.value = std::to_string(tree_to_shwi(operand_tree));
            }
            break;

            // case POLY_INT_CST:

        case REAL_CST: {
            char buf[64];
            real_to_decimal(buf, &TREE_REAL_CST(operand_tree), sizeof(buf), 0, 1);
            constant_operand.value = buf;
        }
        break;

            // case FIXED_CST:
            // case COMPLEX_CST:
            // case VECTOR_CST:

        case STRING_CST:
            constant_operand.value = std::string("\"") + TREE_STRING_POINTER(operand_tree) + "\"";
            break;

            // case PTRMEM_CST:

        default:
            return Core::ConstantOperand{Core::TypeId::invalid(), "<unhandled_constant>"};
        }

        reporter.report(Core::DiagnosticLevel::Debug, "Parsed constant operand with value: " + constant_operand.value);

        return constant_operand;
    }

    // handle base variables
    if (DECL_P(operand_tree) || TREE_CODE(operand_tree) == SSA_NAME)
    {
        reporter.report(Core::DiagnosticLevel::Debug, "Processing operand as variable operand...");

        Core::VariableOperand var_op;
        var_op.id = getOrCreateVariable(operand_tree);
        return var_op;
    }

    // handle recursive access paths (component_ref, bit_field_ref, array_ref, indirect_ref, addr_expr, mem_ref)
    switch (TREE_CODE(operand_tree))
    {
    case COMPONENT_REF: {
        reporter.report(Core::DiagnosticLevel::Debug, "Recursively parsing component reference operand...");
        Core::Operand base_op = parseOperand(TREE_OPERAND(operand_tree, 0));

        Core::VariableOperand *var_op = std::get_if<Core::VariableOperand>(&base_op);
        if (var_op)
        {
            Core::FieldAccessor field_acc;
            field_acc.field_id = getOrCreateVariable(TREE_OPERAND(operand_tree, 1));
            var_op->access_path.push_back(Core::Accessor{Core::AccessorKind::FIELD, std::move(field_acc)});
            var_op->result_type_id = getOrCreateType(TREE_TYPE(operand_tree));
            return *var_op;
        }

        return base_op;
    }
    break;

    case BIT_FIELD_REF: {
        reporter.report(Core::DiagnosticLevel::Debug, "Recursively parsing bit-field reference operand...");
        Core::Operand base_op = parseOperand(TREE_OPERAND(operand_tree, 0));

        Core::VariableOperand *var_op = std::get_if<Core::VariableOperand>(&base_op);
        if (var_op)
        {
            Core::BitSliceAccessor bit_acc{0, 0};
            tree size_tree = TREE_OPERAND(operand_tree, 1);
            tree pos_tree = TREE_OPERAND(operand_tree, 2);

            if (size_tree && tree_fits_uhwi_p(size_tree))
            {
                bit_acc.bit_size = tree_to_uhwi(size_tree);
            }
            else
            {
                reporter.report(
                    Core::DiagnosticLevel::Warning,
                    "Bit-field reference has a size that is unknown or too large to fit in an unsigned integer (" +
                        std::to_string(tree_to_uhwi(size_tree)) + "), treating as having unknown size");
            }

            if (pos_tree && tree_fits_uhwi_p(pos_tree))
            {
                bit_acc.bit_start = tree_to_uhwi(pos_tree);
            }
            else
            {
                reporter.report(
                    Core::DiagnosticLevel::Warning,
                    "Bit-field reference has a position that is unknown or too large to fit in an unsigned integer (" +
                        std::to_string(tree_to_uhwi(pos_tree)) + "), treating as having unknown position");
            }

            var_op->access_path.push_back(Core::Accessor{Core::AccessorKind::BIT_SLICE, std::move(bit_acc)});
            return *var_op;
        }

        return base_op;
    }
    break;

    case ARRAY_REF: {
        reporter.report(Core::DiagnosticLevel::Debug, "Recursively parsing array reference operand...");
        Core::Operand base_op = parseOperand(TREE_OPERAND(operand_tree, 0));

        Core::VariableOperand *var_op = std::get_if<Core::VariableOperand>(&base_op);
        if (var_op)
        {
            Core::ArrayAccessor arr_acc;
            arr_acc.index = parseOperand(TREE_OPERAND(operand_tree, 1));
            var_op->access_path.push_back(Core::Accessor{Core::AccessorKind::ARRAY, std::move(arr_acc)});
            var_op->result_type_id = getOrCreateType(TREE_TYPE(operand_tree));
            return *var_op;
        }

        return base_op;
    }
    break;

        // case ARRAY_RANGE_REF:

    case INDIRECT_REF: {
        reporter.report(Core::DiagnosticLevel::Debug, "Recursively parsing indirect reference operand...");
        Core::Operand ptr_op = parseOperand(TREE_OPERAND(operand_tree, 0));

        Core::VariableOperand *var_op = std::get_if<Core::VariableOperand>(&ptr_op);
        if (var_op)
        {
            var_op->access_path.push_back(Core::Accessor{Core::AccessorKind::DEREF, Core::DerefAccessor{}});
            var_op->result_type_id = getOrCreateType(TREE_TYPE(operand_tree));
            return *var_op;
        }

        return ptr_op;
    }
    break;

    case ADDR_EXPR: {
        reporter.report(Core::DiagnosticLevel::Debug, "Recursively parsing address-of operand...");
        Core::Operand x_op = parseOperand(TREE_OPERAND(operand_tree, 0));

        Core::VariableOperand *var_op = std::get_if<Core::VariableOperand>(&x_op);
        if (var_op)
        {
            Core::AddressOfAccessor addr_acc;
            addr_acc.target_type_id = getOrCreateType(TREE_TYPE(operand_tree));
            var_op->access_path.push_back(Core::Accessor{Core::AccessorKind::ADDRESS_OF, std::move(addr_acc)});
            var_op->result_type_id = getOrCreateType(TREE_TYPE(operand_tree));
            return *var_op;
        }

        return x_op;
    }
    break;

        // case TARGET_MEM_REF:

    case MEM_REF: {
        reporter.report(Core::DiagnosticLevel::Debug, "Recursively parsing memory reference operand...");
        Core::Operand ptr_op = parseOperand(TREE_OPERAND(operand_tree, 0));

        Core::VariableOperand *var_op = std::get_if<Core::VariableOperand>(&ptr_op);
        if (var_op)
        {
            tree offset_tree = TREE_OPERAND(operand_tree, 1);
            if (offset_tree && !integer_zerop(offset_tree))
            {
                Core::OffsetAccessor off_acc;
                off_acc.offset = parseOperand(offset_tree);
                var_op->access_path.push_back(Core::Accessor{Core::AccessorKind::OFFSET, std::move(off_acc)});
            }

            var_op->access_path.push_back(Core::Accessor{Core::AccessorKind::DEREF, Core::DerefAccessor{}});
            var_op->result_type_id = getOrCreateType(TREE_TYPE(operand_tree));
            return *var_op;
        }

        return ptr_op;
    }
    break;

        // case UNCONSTRAINED_ARRAY_REF:
        // case OFFSET_REF:
        // case SCOPE_REF:
        // case MEMBER_REF:

    default:
        break;
    }

    reporter.report(Core::DiagnosticLevel::Warning,
                    "Operand tree code not handled: " + std::to_string(TREE_CODE(operand_tree)));

    return Core::ConstantOperand{Core::TypeId::invalid(), "<unhandled_operand>"};
}

static Core::OpCode mapTreeCodeToOpCode(enum tree_code code)
{
    switch (code)
    {
    // arithmetic
    case PLUS_EXPR:
        return Core::OpCode::ADD;
    case MINUS_EXPR:
        return Core::OpCode::SUB;
    case MULT_EXPR:
        return Core::OpCode::MUL;
    case RDIV_EXPR:
    case TRUNC_DIV_EXPR:
    case CEIL_DIV_EXPR:
    case FLOOR_DIV_EXPR:
    case ROUND_DIV_EXPR:
    case EXACT_DIV_EXPR:
        return Core::OpCode::DIV;
    case TRUNC_MOD_EXPR:
    case CEIL_MOD_EXPR:
    case FLOOR_MOD_EXPR:
    case ROUND_MOD_EXPR:
        return Core::OpCode::MOD;

    // bitwise
    case BIT_AND_EXPR:
        return Core::OpCode::BIT_AND;
    case BIT_IOR_EXPR:
        return Core::OpCode::BIT_OR;
    case BIT_XOR_EXPR:
        return Core::OpCode::BIT_XOR;
    case LSHIFT_EXPR:
        return Core::OpCode::SHL;
    case RSHIFT_EXPR:
        return Core::OpCode::SHR;
    case BIT_NOT_EXPR:
        return Core::OpCode::BIT_NOT;

    // logic
    case TRUTH_AND_EXPR:
    case TRUTH_ANDIF_EXPR:
        return Core::OpCode::LOG_AND;
    case TRUTH_OR_EXPR:
    case TRUTH_ORIF_EXPR:
        return Core::OpCode::LOG_OR;
    case TRUTH_NOT_EXPR:
        return Core::OpCode::LOG_NOT;

    // comparison
    case EQ_EXPR:
        return Core::OpCode::EQUAL;
    case NE_EXPR:
        return Core::OpCode::NOT_EQUAL;
    case LT_EXPR:
        return Core::OpCode::LESS_THAN;
    case LE_EXPR:
        return Core::OpCode::LESS_EQUAL;
    case GT_EXPR:
        return Core::OpCode::GREATER_THAN;
    case GE_EXPR:
        return Core::OpCode::GREATER_EQUAL;

    // unary and others
    case NEGATE_EXPR:
        return Core::OpCode::NEGATE;
    case ABS_EXPR:
        return Core::OpCode::ABS;
    case ADDR_EXPR:
        // address of is handled by operands access path
        return Core::OpCode::NONE;

    case POINTER_PLUS_EXPR:
        return Core::OpCode::POINTER_ADD;
    case POINTER_DIFF_EXPR:
        return Core::OpCode::POINTER_SUB;

    // numeric
    case MIN_EXPR:
        return Core::OpCode::MIN;
    case MAX_EXPR:
        return Core::OpCode::MAX;

    // rotation
    case LROTATE_EXPR:
        return Core::OpCode::ROTATE_LEFT;
    case RROTATE_EXPR:
        return Core::OpCode::ROTATE_RIGHT;

    // casts
    case NOP_EXPR:
    case CONVERT_EXPR:
    case FIX_TRUNC_EXPR:
    case FLOAT_EXPR:
        return Core::OpCode::CAST;

    default:
        return Core::OpCode::NONE;
    }
}

void GCCAdapter::processFunctionParameters(function *fun, Core::Function *function)
{
    reporter.report(Core::DiagnosticLevel::Debug, "Processing function parameters...");

    for (tree arg = DECL_ARGUMENTS(fun->decl); arg; arg = DECL_CHAIN(arg))
    {
        Core::VariableId param_id = getOrCreateVariable(arg);
        function->parameter_ids.push_back(param_id);
    }

    reporter.report(Core::DiagnosticLevel::Debug, "Processed function parameters");
}

void GCCAdapter::registerBasicBlock(basic_block bb)
{
    if (!bb)
    {
        return;
    }

    if (block_cache.find(bb) != block_cache.end())
    {
        return;
    }

    Core::Block *block = model.createBlock();
    block_cache.emplace(bb, block->id);
}

void GCCAdapter::registerBasicBlocks(function *fun)
{
    reporter.report(Core::DiagnosticLevel::Debug,
                    "Registering ALL basic blocks for function " + current_function_name + "...");

    basic_block bb;
    FOR_ALL_BB_FN(bb, fun)
    {
        registerBasicBlock(bb);
    }

    reporter.report(Core::DiagnosticLevel::Debug,
                    "Finished registering ALL basic blocks for function " + current_function_name);
}

void GCCAdapter::linkPredecessorsAndSuccessors(basic_block bb, Core::Block *block)
{
    edge e;
    edge_iterator ei;

    FOR_EACH_EDGE(e, ei, bb->preds)
    {
        auto it = block_cache.find(e->src);
        if (it == block_cache.end())
        {
            reporter.report(Core::DiagnosticLevel::Warning,
                            "Skipping predecessor edge with unresolved source block ID");
            continue;
        }

        block->predecessors.push_back(it->second);
    }

    FOR_EACH_EDGE(e, ei, bb->succs)
    {
        auto it = block_cache.find(e->dest);
        if (it == block_cache.end())
        {
            reporter.report(Core::DiagnosticLevel::Warning,
                            "Skipping successor edge with unresolved destination block ID");
            continue;
        }

        block->successors.push_back(it->second);
    }
}

void GCCAdapter::processInstruction(gimple *stmt, Core::Block *block)
{
    enum gimple_code gcode = gimple_code(stmt);
    if (gcode == GIMPLE_PREDICT)
    {
        reporter.report(Core::DiagnosticLevel::Debug,
                        "Skipping GIMPLE_PREDICT statement as it does not affect semantics");
        return;
    }

    Core::Instruction *instruction = model.createInstruction();
    reporter.report(Core::DiagnosticLevel::Debug, "Processing instruction with ID: " + std::to_string(instruction->id));

    // add instruction to parent block
    block->instruction_ids.push_back(instruction->id);

    instruction->parent_block_id = block->id;

    switch (gcode)
    {
        // case GIMPLE_ERROR_MARK:
    case GIMPLE_COND: {
        Core::CondInstruction cond;
        instruction->kind = Core::InstructionKind::COND;

        // TODO: use `as_a`
        // gcond *cond_stmt = as_a<gcond *>(stmt);

        basic_block bb = gimple_bb(stmt);
        if (bb)
        {
            edge e;
            edge_iterator ei;
            FOR_EACH_EDGE(e, ei, bb->succs)
            {
                if (e->flags & EDGE_TRUE_VALUE)
                {
                    auto target_it = block_cache.find(e->dest);
                    if (target_it != block_cache.end())
                    {
                        cond.true_target = target_it->second;
                    }
                    else
                    {
                        reporter.report(Core::DiagnosticLevel::Warning,
                                        "Unresolved true target block for COND instruction");
                        cond.true_target = Core::BlockId::invalid();
                    }
                }
                else if (e->flags & EDGE_FALSE_VALUE)
                {
                    auto target_it = block_cache.find(e->dest);
                    if (target_it != block_cache.end())
                    {
                        cond.false_target = target_it->second;
                    }
                    else
                    {
                        reporter.report(Core::DiagnosticLevel::Warning,
                                        "Unresolved false target block for COND instruction");
                        cond.false_target = Core::BlockId::invalid();
                    }
                }
            }
        }

        cond.opcode = mapTreeCodeToOpCode(gimple_cond_code(stmt));
        cond.lhs = parseOperand(gimple_cond_lhs(stmt));
        cond.rhs = parseOperand(gimple_cond_rhs(stmt));

        instruction->data = std::move(cond);
    }
    break;
        // case GIMPLE_DEBUG:
    case GIMPLE_GOTO: {
        Core::GotoInstruction goto_instr;
        instruction->kind = Core::InstructionKind::GOTO;

        ggoto *goto_stmt = as_a<ggoto *>(stmt);

        tree dest_label = gimple_goto_dest(goto_stmt);
        basic_block target_bb = label_to_block(cfun, dest_label);
        if (target_bb)
        {
            auto target_it = block_cache.find(target_bb);
            if (target_it != block_cache.end())
            {
                goto_instr.target = target_it->second;
            }
            else
            {
                reporter.report(Core::DiagnosticLevel::Warning, "Unresolved target block for GOTO instruction");
                goto_instr.target = Core::BlockId::invalid();
            }
        }

        instruction->data = std::move(goto_instr);
    }
    break;
    case GIMPLE_LABEL: {
        Core::LabelInstruction label_instr;
        instruction->kind = Core::InstructionKind::LABEL;

        glabel *label_stmt = as_a<glabel *>(stmt);

        tree label_tree = gimple_label_label(label_stmt);
        label_instr.label = parseOperand(label_tree);

        instruction->data = std::move(label_instr);
    }
    break;
    case GIMPLE_SWITCH: {
        Core::SwitchInstruction switch_instr;
        instruction->kind = Core::InstructionKind::SWITCH;

        gswitch *switch_stmt = as_a<gswitch *>(stmt);

        switch_instr.index = parseOperand(gimple_switch_index(switch_stmt));

        for (unsigned i = 0; i < gimple_switch_num_labels(switch_stmt); i++)
        {
            tree case_label = gimple_switch_label(switch_stmt, i);
            Core::SwitchCase switch_case;
            switch_case.source_location = getSourceLocation(EXPR_LOCATION(case_label));

            basic_block target_bb = label_to_block(cfun, CASE_LABEL(case_label));
            if (target_bb)
            {
                auto target_it = block_cache.find(target_bb);
                if (target_it != block_cache.end())
                {
                    switch_case.target_block_id = target_it->second;
                }
            }

            tree low = CASE_LOW(case_label);
            if (low)
            {
                switch_case.low_value = parseOperand(low);
            }

            tree high = CASE_HIGH(case_label);
            if (high)
            {
                switch_case.high_value = parseOperand(high);
            }

            switch_instr.cases.push_back(switch_case);
        }

        instruction->data = std::move(switch_instr);
    }
    break;
    case GIMPLE_ASSIGN: {
        if (gimple_clobber_p(stmt))
        {
            Core::ClobberInstruction clobber;
            instruction->kind = Core::InstructionKind::CLOBBER;

            tree lhs = gimple_assign_lhs(stmt);
            clobber.clobbered_variable = parseOperand(lhs);

            instruction->source_location = getSourceLocation(DECL_SOURCE_LOCATION(lhs));
            instruction->data = std::move(clobber);

            break;
        }

        Core::AssignInstruction assign;
        instruction->kind = Core::InstructionKind::ASSIGN;

        // TODO: use `as_a`
        // gassign *assign_stmt = as_a<gassign *>(stmt);

        tree lhs = gimple_assign_lhs(stmt);
        assign.lhs = parseOperand(lhs);

        // opcode
        enum tree_code rhs_code = gimple_assign_rhs_code(stmt);

        // skip non-clobber CONSTRUCTOR assignments, because they are stored as variable initializers in the old
        // pipeline
        if (rhs_code == CONSTRUCTOR)
        {
            instruction->kind = Core::InstructionKind::NOP;
            break;
        }

        assign.opcode = mapTreeCodeToOpCode(rhs_code);

        enum gimple_rhs_class rhs_class = gimple_assign_rhs_class(stmt);
        switch (rhs_class)
        {
        case GIMPLE_UNARY_RHS:
        case GIMPLE_SINGLE_RHS:
            assign.rhs1 = parseOperand(gimple_assign_rhs1(stmt));
            break;
        case GIMPLE_BINARY_RHS:
            assign.rhs1 = parseOperand(gimple_assign_rhs1(stmt));
            assign.rhs2 = parseOperand(gimple_assign_rhs2(stmt));
            break;
        case GIMPLE_TERNARY_RHS:
            assign.rhs1 = parseOperand(gimple_assign_rhs1(stmt));
            assign.rhs2 = parseOperand(gimple_assign_rhs2(stmt));
            assign.rhs3 = parseOperand(gimple_assign_rhs3(stmt));
            break;
        case GIMPLE_INVALID_RHS:
            break;
        }

        instruction->data = std::move(assign);
    }
    break;

    case GIMPLE_ASM: {
        Core::AsmInstruction asm_instr;
        instruction->kind = Core::InstructionKind::ASM;

        // gasm *asm_stmt = as_a<gasm *>(stmt);

        instruction->data = std::move(asm_instr);
    }
    break;

    case GIMPLE_CALL: {
        Core::CallInstruction call;
        instruction->kind = Core::InstructionKind::CALL;

        // TODO: use `as_a`
        // gcond *cond_stmt = as_a<gcond *>(stmt);

        tree fndecl = gimple_call_fndecl(stmt);
        if (fndecl && DECL_BUILT_IN_CLASS(fndecl) == BUILT_IN_NORMAL)
        {
            enum built_in_function code = DECL_FUNCTION_CODE(fndecl);
            switch (code)
            {
                // TODO: handle built-in functions
            default:
                reporter.report(Core::DiagnosticLevel::Debug,
                                "Processing a normal function call to built-in function with code: " +
                                    std::to_string(code));
                break;
            }
        }

        if (gimple_call_internal_p(stmt))
        {
            internal_fn ifn = gimple_call_internal_fn(stmt);
            const char *fn_name = internal_fn_name(ifn);
            std::string fn_str = fn_name ? fn_name : "<internal>";

            // lazily create a synthetic function type for internal builtins
            if (!builtin_fn_type_id.isValid())
            {
                Core::Type *t = model.createType();
                t->name = "<builtin_fnc_type>";
                t->kind = Core::TypeKind::FUNCTION;
                t->data = Core::FunctionType{};
                builtin_fn_type_id = t->id;
            }

            auto it = internal_fn_cache.find(fn_str);
            if (it == internal_fn_cache.end())
            {
                Core::Variable *v = model.createVariable();
                v->name = fn_str;
                v->type_id = builtin_fn_type_id;
                v->artificial = true;
                internal_fn_cache[fn_str] = v->id;
                call.callee = Core::VariableOperand{v->id, {}, std::nullopt};
            }
            else
            {
                call.callee = Core::VariableOperand{it->second, {}, std::nullopt};
            }
        }
        else
        {
            tree fn = gimple_call_fn(stmt);
            call.callee = parseOperand(fn);
        }

        // return value
        tree lhs = gimple_call_lhs(stmt);
        if (lhs)
        {
            call.lhs = parseOperand(lhs);
        }
        else
        {
            call.lhs = std::nullopt;
        }

        // arguments
        for (unsigned i = 0; i < gimple_call_num_args(stmt); ++i)
        {
            call.arguments.push_back(parseOperand(gimple_call_arg(stmt, i)));
        }

        instruction->data = std::move(call);
    }
    break;
        // case GIMPLE_TRANSACTION:
    case GIMPLE_RETURN: {
        Core::ReturnInstruction ret;
        instruction->kind = Core::InstructionKind::RETURN;

        greturn *ret_stmt = as_a<greturn *>(stmt);

        tree retval = gimple_return_retval(ret_stmt);
        if (retval)
        {
            ret.return_value = parseOperand(retval);
        }
        else
        {
            ret.return_value = std::nullopt;
        }

        instruction->data = std::move(ret);
    }
    break;
    // case GIMPLE_BIND:
    // case GIMPLE_CATCH:
    // case GIMPLE_EH_FILTER:
    // case GIMPLE_EH_MUST_NOT_THROW:
    // case GIMPLE_EH_ELSE:
    // case GIMPLE_RESX:
    // case GIMPLE_EH_DISPATCH:
    case GIMPLE_PHI: {
        Core::PhiInstruction phi;
        instruction->kind = Core::InstructionKind::PHI;

        gphi *phi_stmt = as_a<gphi *>(stmt);

        phi.lhs = parseOperand(gimple_phi_result(phi_stmt));

        for (unsigned i = 0; i < gimple_phi_num_args(phi_stmt); i++)
        {
            tree arg_tree = gimple_phi_arg_def(phi_stmt, i);
            edge incoming_edge = gimple_phi_arg_edge(phi_stmt, i);

            Core::BlockId src_block_id = Core::BlockId::invalid();
            if (incoming_edge->src && block_cache.find(incoming_edge->src) != block_cache.end())
            {
                src_block_id = block_cache[incoming_edge->src];
            }
            else
            {
                reporter.report(Core::DiagnosticLevel::Warning,
                                "Unresolved source block for PHI argument, using invalid block ID");
            }

            Core::PhiIncomingValue incoming_value;
            incoming_value.block_id = src_block_id;
            incoming_value.value = parseOperand(arg_tree);

            phi.incoming_values.push_back(std::move(incoming_value));
        }

        instruction->data = std::move(phi);
    }
    break;
    // case GIMPLE_TRY:
    // case GIMPLE_NOP:
    // case GIMPLE_OMP_ATOMIC_LOAD:
    // case GIMPLE_OMP_ATOMIC_STORE:
    // case GIMPLE_OMP_CONTINUE:
    // case GIMPLE_OMP_CRITICAL:
    // case GIMPLE_OMP_FOR:
    // case GIMPLE_OMP_MASTER:
    // case GIMPLE_OMP_MASKED:
    // case GIMPLE_OMP_TASKGROUP:
    // case GIMPLE_OMP_PARALLEL:
    // case GIMPLE_OMP_TASK:
    // case GIMPLE_OMP_RETURN:
    // case GIMPLE_OMP_SCAN:
    // case GIMPLE_OMP_SCOPE:
    // case GIMPLE_OMP_SECTION:
    // case GIMPLE_OMP_SECTIONS:
    // case GIMPLE_OMP_SECTIONS_SWITCH:
    // case GIMPLE_OMP_SINGLE:
    // case GIMPLE_OMP_TARGET:
    // case GIMPLE_OMP_TEAMS:
    // case GIMPLE_OMP_ORDERED:
    // case GIMPLE_PREDICT:
    // case GIMPLE_WITH_CLEANUP_EXPR:
    // case LAST_AND_UNUSED_GIMPLE_CODE:
    //     break;
    default:
        reporter.report(Core::DiagnosticLevel::Warning,
                        "Encountered an unhandled gimple code: " + std::string(gimple_code_name[gcode]));

        Core::UnknownInstruction unknown;
        unknown.description = "Unhandled gimple code: " + std::string(gimple_code_name[gcode]);
        instruction->data = std::move(unknown);

        break;
    }

    if (gcode == GIMPLE_CALL && (gimple_call_flags(stmt) & ECF_NORETURN))
    {
        Core::Instruction *abort_instr = model.createInstruction();
        block->instruction_ids.push_back(abort_instr->id);
        abort_instr->parent_block_id = block->id;
        abort_instr->kind = Core::InstructionKind::ABORT;
        abort_instr->data = Core::AbortInstruction{};
        abort_instr->source_location = instruction->source_location;
        // abort_instr->is_terminator = true;
    }

    instruction->source_location = getSourceLocation(enhanceLocationT(gimple_location(stmt), gcode, stmt));

    reporter.report(Core::DiagnosticLevel::Debug, "Processed instruction with ID: " + std::to_string(instruction->id));
}

void GCCAdapter::processInstructions(basic_block bb, Core::Block *block)
{
    // process phi nodes
    // NOTE: this is skipped entirely in "cfg" stage of compilation, but would run automatically with "ssa"
    for (gphi_iterator gpi = gsi_start_phis(bb); !gsi_end_p(gpi); gsi_next(&gpi))
    {
        gphi *phi_stmt = gpi.phi();
        if (!phi_stmt)
        {
            continue;
        }

        processInstruction(phi_stmt, block);
    }

    // process regular statements
    for (gimple_stmt_iterator gsi = gsi_start_bb(bb); !gsi_end_p(gsi); gsi_next(&gsi))
    {
        gimple *stmt = gsi_stmt(gsi);
        if (!stmt)
        {
            continue;
        }

        processInstruction(stmt, block);
    }
}

void GCCAdapter::processBasicBlock(basic_block bb, Core::FunctionId function_id)
{
    auto it = block_cache.find(bb);
    if (it == block_cache.end())
    {
        reporter.report(Core::DiagnosticLevel::Warning,
                        "Encountered a block without a pre-registered ID, creating a new one...");
        Core::Block *new_block = model.createBlock();
        it = block_cache.emplace(bb, new_block->id).first;
    }

    Core::Block *block = model.getBlockMutable(it->second);
    reporter.report(Core::DiagnosticLevel::Debug, "Processing basic block with ID: " + std::to_string(block->id));

    block->parent = function_id;

    if (bb->index == ENTRY_BLOCK)
    {
        block->name = "ENTRY";
    }
    else if (bb->index == EXIT_BLOCK)
    {
        block->name = "EXIT";
    }
    else
    {
        block->name = "bb_" + std::to_string(bb->index);
    }
    reporter.report(Core::DiagnosticLevel::Debug, "Basic block name set to: " + block->name);

    linkPredecessorsAndSuccessors(bb, block);

    if (bb->index != ENTRY_BLOCK && bb->index != EXIT_BLOCK)
    {
        processInstructions(bb, block);
    }
}

void GCCAdapter::processBasicBlocks(function *fun, Core::Function *function)
{
    reporter.report(Core::DiagnosticLevel::Debug,
                    "Processing ALL basic blocks for function " + current_function_name + "...");

    basic_block bb;
    FOR_ALL_BB_FN(bb, fun)
    {
        processBasicBlock(bb, function->id);
        function->block_ids.push_back(block_cache[bb]);
    }

    reporter.report(Core::DiagnosticLevel::Debug,
                    "Finished processing ALL basic blocks for function " + current_function_name);
}

void GCCAdapter::processFunction(function *fun)
{
    if (!fun || !fun->decl || DECL_NAME(fun->decl) == nullptr)
    {
        reporter.report(Core::DiagnosticLevel::Warning, "Adapter encountered a function without a name");
        return;
    }

    // save the current function name for source location tracking
    // TODO: maybe bring the function name through function arguments instead of Adapter attribute
    current_function_name = function_name(fun);
    reporter.report(Core::DiagnosticLevel::Debug, std::string("Adapter processing function: ") + current_function_name);

    // start processing function
    Core::Function *function = model.createFunction();
    reporter.report(Core::DiagnosticLevel::Debug, "Function ID: " + std::to_string(function->id));

    // clear the basic block cache since GCC may reuse basic_block pointer values across functions
    block_cache.clear();

    function->name = function_name(fun);
    reporter.report(Core::DiagnosticLevel::Debug, "Function name set to: " + function->name);

    // process function return type
    if (TREE_TYPE(fun->decl))
    {
        tree_node *return_type = TREE_TYPE(TREE_TYPE(fun->decl));
        if (return_type)
        {
            function->return_type_id = getOrCreateType(return_type);
            reporter.report(Core::DiagnosticLevel::Debug,
                            "Function return type ID: " + std::to_string(function->return_type_id));
        }
    }

    // process function source location
    if (fun->decl)
    {
        function->source_location = getSourceLocation(DECL_SOURCE_LOCATION(fun->decl));
    }

    processFunctionParameters(fun, function);

    // process local variables
    if (fun->local_decls)
    {
        tree var;
        unsigned i;
        FOR_EACH_VEC_SAFE_ELT(fun->local_decls, i, var)
        {
            if (TREE_CODE(var) != VAR_DECL)
            {
                continue;
            }

            // filter out artificial variables or those not in the source
            if (DECL_ARTIFICIAL(var))
            {
                continue;
            }

            Core::VariableId var_id = getOrCreateVariable(var);
            function->local_variable_ids.push_back(var_id);
        }
    }

    if (fun->cfg)
    {
        registerBasicBlocks(fun);
        processBasicBlocks(fun, function);
    }
    else
    {
        reporter.report(Core::DiagnosticLevel::Error, "Function has no control flow graph");
    }

    reporter.report(Core::DiagnosticLevel::Debug, "Processed function with ID: " + std::to_string(function->id));
}

} // namespace CodeListener::CompilerAbstractionLayer
